### ISSUE TITLE
Enabling deeper analysis of user activities on site through GTM/GA

### ISSUE THREAD

**Issue by robertsky** [hackerspacesg/hackerspace.sg#150]
## Goals

- Tracking user interactions on all pages:
  - [x] Track site link clicks in body and navbar.
  - ~~Track link clicks to hsg assets such as Google Groups, Facebook Group/Page, Twitter, etc~~ Outbound link
  - [x] Track mailto clicks
  - [x] Track downloads
  - [x] Scroll tracking on individual pages by percentages
  - [x] ~~Track footer link clicks~~ Track outbound links
- Tracking user interactions on specific pages:
  - Home
    - ~~Events block - clicks on event links~~ Track as outbound links
    - [x] Clicks on links in Twitter widget (need research)
  - Calendar
    - ~~When user scrolls to individual sections~~ percentage page scrolling
    - ~~Clicks on links in Google Calendar (need research)~~
  - Location
    - ~~Google Maps interaction (need research)~~ no relevant events to track for, i.e. directions or save.
    - ~~Clicks on location links~~ Track outbound links
  - Membership
    - ~~Clicks on Paypal subscription buttons~~ requires advanced setup. for future implementation
  - About
    - ~~Clicks on exit links to media sites~~ Track outbound links
- [x] Dissociate live, staging/dev site data on Google Analytics
  - Currently, all traffic data is sent to one GA property. Ideally, staging/dev data should be in another GA property

## Implementation steps/Task list

- [x] Set up Google Tag Manager. GTM ID: GTM-M3BQNB
- [x] Set up dev/staging GA property. GA ID: UA-11667249-4
- [x] Fix up Google Search Console.
- [x] Add classes to HTML Elements if required.
- [x] Set up page tracking in Google Tag Manager
- Set up event tracking by page in Google Tag Manager.

Note:
Look for me for access to GTM and/or GA property. Doing this in my free time.
